### ISSUE TITLE
DistMult running error

### ISSUE THREAD

**Issue by null-id** [yangji9181/HNE#10]
Sorry, since the issue https://github.com/yangji9181/HNE/issues/9 is closed. I reopen this issue.

I installed spodernet. However,

```python
>>> import spodernet
>>> import spodernet.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spodernet.utils'
```

As you can see, spodernet is imported normally. But utils not found.

**Comment by xiaoyuxin1002** [comment]
spodernet is a package written by the author of ConvE. You can find the source [here](https://github.com/TimDettmers/spodernet).
Can you check if you have successfully download that package? If so, then you should be able to find the utils module based on this [hierarchy](https://github.com/TimDettmers/spodernet/tree/master/spodernet/utils).
