### ISSUE TITLE
Error in MAGNN

### ISSUE THREAD

**Issue by justicevita** [yangji9181/HNE#14]
my dgl version is 0.5.2
in MAGNN utils.py line 206:
g.from_network(ng)
raise an error: 
raise DGLError('DGLGraph.from_networkx is deprecated. Please call the following\n\n'
dgl._ffi.base.DGLError: DGLGraph.from_networkx is deprecated. Please call the following
dgl.from_networkx(nx_graph, node_attrs, edge_attrs)
, which creates a new DGLGraph from the networkx graph.

**Comment by PiggyGaGa** [comment]
you can use dgl 0.3 version

**Comment by xiaoyuxin1002** [comment]
Thanks for pointing it out! The codes have been updated to work with dgl-cu101 0.5.2
