### ISSUE TITLE
dgl version conflict

### ISSUE THREAD

**Issue by PiggyGaGa** [yangji9181/HNE#15]
When I run MAGNN model, the dgl version matches 0.3, but this version is not suit for R-GCN model. I see this awesome rep contains 13 algorithms, they all have original git rep. So there may be conflict in some packages, if anyone successfully run all algorithms, it will be very nice to provide the version of the important packages such as dgl

**Comment by xiaoyuxin1002** [comment]
Since we refactor the codes from the original implementation for most of the 13 algorithms, there may be some inconsistency among the versions of packages used. Sorry about that. Our plan is to update the codes as soon as possible if someone reports an issue with the versioning.
