### ISSUE TITLE
unsupervised training with HAN and MAGNN

### ISSUE THREAD

**Issue by Luokejin** [yangji9181/HNE#17]
Happy new year! I got a problem in running the code of HAN and MAGNN with unsuperviesd training, using Yelp's data. And this problem is that these codes run out of my 16G memory. ( T^T )  I am not sure that there are another problems，but I wonder if it's related to data's link number ? Also I want to ask whether there are any ways to help me run this code, such as minibatch?
Then I also try to use my data on MAGNN, which occurred the problem that the items numbers of " batch_node_features " and "batch_targets"  are not equal. So that when compute the unsupervised loss, the node_features will occur the Keyword Error. ( Of course, the PubMed runs well )  So I think there is something wrong with my path.dat file , I can't figure out what problem is.

**Comment by xiaoyuxin1002** [comment]
I believe that our implementation of HAN and MAGNN support minibatch training. You may wish to take a look at the relevant parameters in run.sh such as batch_size, neigh_por, sampling, etc.
Regarding your own datasets, batch_node_features are the features of your targeting nodes. So you may wish to take a look at the outputs of prepare_minibatch and see if they are what you would expect based on the meta paths specified in your path.dat

**Comment by esprit1995** [comment]
Hello. 
I also tried training MAGNN on unattributed PubMed with the default parameters (unchanged after cloning your repository). It happily consumed all 32  gigs of RAM I had available and crashed. Am I doing something wrong? How much RAM did you need while testing MAGNN to get results for your paper?
