### ISSUE TITLE
Question about R-GCN training

### ISSUE THREAD

**Issue by xianshu1** [yangji9181/HNE#18]
In model.eval(), it iterate through every batch to get node embeddings.
main.py line 112: `for batch_num in range(batch_total)`

I am wondering why in model.train(), you don't iterate through all batch in each epoch?

**Comment by xiaoyuxin1002** [comment]
Sometimes the graph size is so large that it is impractical to loop through the entire graph via mini-batches in every epoch. So instead of setting the number of training epochs, we intend to set the number of training batches in model.train() and expect the model to exhibit inductive ability.
