### ISSUE TITLE
HAN kill!

### ISSUE THREAD

**Issue by HodaMemar** [yangji9181/HNE#22]
Hello
Thanks for this valuable work
I try to run HAN on colab
I install PyTorch
and after run transform.sh , try to execute run.sh in the HAN folder
but I see this message in the orange box
![image](https://user-images.githubusercontent.com/66674325/128379809-6791d530-ecb8-495a-b634-0136c5c1e607.png)
could you please guide me in this issue? 
Thank you

**Comment by HodaMemar** [comment]
Also, I try to run PTE.
and get this error:
![image](https://user-images.githubusercontent.com/66674325/128380890-b8c10d1c-4fe9-4a0b-8e62-7efd0804033b.png)
This is while file makefile exists 
Would you please tell me your opinion?
Thanks

**Comment by HodaMemar** [comment]
Could this be related to settings on the colab?

**Comment by xiaoyuxin1002** [comment]
For your first issue, it is very likely that colab was running out of memory. Can you try a smaller dataset like PubMed and see if that issue still occurs?

For your second issue, I am not pretty sure. Can you try 
(1) rename makefile to Makefile and see if it works? 
(2) chang Line 10 in run.sh to "make -f makefile" and see if it works? 
(3) try to run metapath2vec-ESim (which also has a make command in run.sh) and see if it works?

**Comment by HodaMemar** [comment]
Thank you for your response.
I will check these cases and write the result

**Comment by HodaMemar** [comment]
Hi
![image](https://user-images.githubusercontent.com/66674325/129141134-6b669eaf-992d-4113-b1f5-c29cd2c83d44.png)

I try by PubMed
Unfortunately, I encountered a new error
