### ISSUE TITLE
Negative samples

### ISSUE THREAD

**Issue by snash4** [yangji9181/HNE#3]
Hi, 
 DistMult uses negative sampling for the training...
I couldn't find Negative sampling parameter in the algo.
How did you generate the negative samples and how many NS per positive triplet?

**Comment by xiaoyuxin1002** [comment]
This implementation of DistMult essentially considers all the nodes not linked to the targeting node as negative triplets.
You can find the corresponding codes (function name: TargetIdx2MultiTarget) in the spodernet package [https://github.com/TimDettmers/spodernet/blob/master/spodernet/preprocessing/processors.py](url) used in the implementation.
Thanks!

**Comment by snash4** [comment]
thanks for the answer and for the quick responses.
