### ISSUE TITLE
Segmentation Fault [TransE]

### ISSUE THREAD

**Issue by snash4** [yangji9181/HNE#4]
Hi, 
 I tried to run TranE on two different datasets. Both times it throws segmentation fault.
**### Program terminated with signal 11, Segmentation fault.
#0  _int_malloc (av=av@entry=0x7fda5cf9b760 <main_arena>, bytes=bytes@entry=800000) at malloc.c:3780
3780	      set_head(remainder, remainder_size | PREV_INUSE);**

It works on PubMed and my other dataset (133k triplets)
Any pointers to solve this problem.. 

ps: The system has around 700 Gb ram...

**Comment by xiaoyuxin1002** [comment]
Sorry, I am not quite sure about that. 
Can you trace back to the implementation of TransE and provide more information about which line in transE.cpp caused the fault?
